inherit_from: ../../.rubocop.yml

# Component-specific overrides
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - '*.rb'
    - 'examples/**/*.rb'

Metrics/AbcSize:
  Max: 20
