# frozen_string_literal: true

source 'https://rubygems.org'

gem 'language-operator', '~> 0.1.46'

# Tool server dependencies
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'rackup', '~> 2.1'
gem 'puma', '~> 6.4'
gem 'json', '~> 2.7'

group :development do
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
end
