name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  create:
    tags:
      - 'v*'

jobs:
  test:
    name: Test & Lint
    runs-on: builder

    steps:
      - name: Checkout code
        uses: https://github.com/actions/checkout@v4

      - name: Set up Ruby
        uses: https://github.com/ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint

      - name: Build gem
        run: make build

      - name: Save gem artifact
        run: |
          mkdir -p /tmp/artifacts
          cp *.gem /tmp/artifacts/ 2>/dev/null || true

  publish:
    name: Publish Gem
    runs-on: builder
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: https://github.com/actions/checkout@v4

      - name: Set up Ruby
        uses: https://github.com/ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Build gem
        run: make build

      - name: Extract version from tag
        id: tag_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing version: $VERSION"

      - name: Verify version matches
        run: |
          GEM_VERSION=$(ruby -r ./lib/language_operator/version -e 'puts LanguageOperator::VERSION')
          TAG_VERSION="${{ steps.tag_version.outputs.version }}"
          if [ "$GEM_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Gem version ($GEM_VERSION) does not match tag version ($TAG_VERSION)"
            exit 1
          fi
          echo "Version check passed: $GEM_VERSION"

      - name: Create Release
        run: |
          echo "Release ${{ steps.tag_version.outputs.version }}" > /tmp/release_notes.txt
          echo "" >> /tmp/release_notes.txt
          echo "## Installation" >> /tmp/release_notes.txt
          echo "" >> /tmp/release_notes.txt
          echo "\`\`\`bash" >> /tmp/release_notes.txt
          echo "gem install language-operator -v ${{ steps.tag_version.outputs.version }}" >> /tmp/release_notes.txt
          echo "\`\`\`" >> /tmp/release_notes.txt
          echo "" >> /tmp/release_notes.txt
          echo "## Changes" >> /tmp/release_notes.txt
          echo "" >> /tmp/release_notes.txt
          echo "See [CHANGELOG.md](CHANGELOG.md) for details." >> /tmp/release_notes.txt

          # Create release notes
          echo "Created release notes for version ${{ steps.tag_version.outputs.version }}"
          cat /tmp/release_notes.txt

      - name: Publish to RubyGems (if configured)
        if: env.RUBYGEMS_API_KEY != ''
        run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF
          chmod 0600 ~/.gem/credentials
          gem push language-operator-*.gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

      - name: Archive gem
        run: |
          mkdir -p /tmp/artifacts
          cp *.gem /tmp/artifacts/
          ls -lh /tmp/artifacts/
          echo "Gem artifact saved to /tmp/artifacts/"
