# frozen_string_literal: true

source 'https://rubygems.org'

gem 'language-operator', '~> 0.1.59'

# Agent-specific dependencies for autonomous execution
gem 'concurrent-ruby', '~> 1.3'
gem 'rufus-scheduler', '~> 3.9'

group :development do
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
end
